---
title: "Asignacion"
author: "David Murillo"
format: html
---

## Ejercicio 1

Con la base de datos "penguins_size.csv", sigue las siguientes instrucciones:

- Cargar la base de datos:

Utiliza las funciones necesarias para cargar la base de datos "penguins_size.csv" en tu entorno de trabajo. Asegúrate de tener acceso a la información contenida en el conjunto de datos.

- Filtrar por sexo Hembra:

Aplica las funciones adecuadas para filtrar únicamente las observaciones correspondientes al sexo femenino en el conjunto de datos. De esta manera, obtendrás un subconjunto que incluye solo las hembras.

- Seleccionar una isla en específico:

Selecciona una isla específica del conjunto de datos utilizando las funciones apropiadas. Puedes elegir la isla que prefieras y filtrar las observaciones correspondientes a esa ubicación.

- Presentar el resumen de alguna variable, por sexo y por isla:

Utiliza funciones de resumen estadístico para presentar información relevante sobre alguna variable de interés, considerando la distinción por sexo y por isla. Puede ser útil visualizar esta información de manera clara y comprensible.
 
 